version: '3.8'
services:
  db:
    image: mysql:8
    container_name: mysql
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build: ./jobtracking_api
    container_name: BackendApplication
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./jobtracking_ui
    container_name: UIApplication
    ports:
      -  "4200:4200"
    depends_on:
      - backend

volumes:
  db_data:
